Repository RehanSaeed/Schema.NET, pull requests merged in 2021-11, with the labels that each got.

#100 Switch to System.Text.Json
  Benchmarks/Schema.NET.Benchmarks/SchemaBenchmarkBase.cs
  Schema.NET.sln
  Source/Common/Constants.cs
  Source/Common/ContextJsonConverter.cs
  Source/Common/DateTimeToIso8601DateValuesJsonConverter.cs
  Source/Common/EnumHelper.cs
  Source/Common/JsonLdContext.cs
  Source/Common/JsonLdObject.cs
  Source/Common/SchemaEnumJsonConverter{T}.cs
  Source/Common/SchemaSerializer.cs
  Source/Common/Thing.Partial.cs
  Source/Common/TimeSpanToISO8601DurationValuesJsonConverter.cs
  Source/Common/ValuesJsonConverter.cs
  Source/Schema.NET.Pending/Schema.NET.Pending.csproj
  Source/Schema.NET/Schema.NET.csproj
  Tests/Schema.NET.Test/DateValuesJsonConverterTest.cs
  Tests/Schema.NET.Test/DurationValuesJsonConverterTest.cs
  Tests/Schema.NET.Test/Examples/JobPostingTest.cs
  Tests/Schema.NET.Test/Examples/RecipeTest.cs
  Tests/Schema.NET.Test/Examples/RestaurantTest.cs
  Tests/Schema.NET.Test/Models/ExternalSchemaModelCustomNamespace.cs
  Tests/Schema.NET.Test/Models/ExternalSchemaModelSharedNamespace.cs
  Tests/Schema.NET.Test/ThingTest.cs
  Tests/Schema.NET.Test/ValuesJsonConverterTest.cs
  Tools/Schema.NET.Tool/SchemaSourceGenerator.cs
Labels: enhancement, major

#361 Fix images in embedded NuGet package README.md
  README.md
Labels: patch, documentation

#360 Upgrade Windows image to VS 2022
  Schema.NET.sln
  Tools/Schema.NET.Tool/SchemaSourceGenerator.cs
  appveyor.yml
Labels: maintenance, patch

#364 Bump Cake.Tool from 1.3.0 to 2.0.0
  build.cake
  dotnet-tools.json
Labels: maintenance, patch
