Repository RehanSaeed/Schema.NET, pull requests merged in 2021-03, with the labels that each got.

#253 Fix VS 16.9 Warnings
  .editorconfig
  Source/Schema.NET/DateTimeHelper.cs
  Source/Schema.NET/FastActivator.cs
  Source/Schema.NET/HashCode.cs
  Source/Schema.NET/OneOrMany{T}.cs
  Source/Schema.NET/SchemaSerializer.cs
  Source/Schema.NET/ValuesJsonConverter.cs
  Source/Schema.NET/Values{T1,T2,T3,T4,T5,T6,T7}.cs
  Source/Schema.NET/Values{T1,T2,T3,T4}.cs
  Source/Schema.NET/Values{T1,T2,T3}.cs
  Source/Schema.NET/Values{T1,T2}.cs
  Tests/Schema.NET.Test/MixedTypesTest.cs
  Tests/Schema.NET.Test/SerializationTest.cs
  Tests/Schema.NET.Test/ThingTest.cs
  Tests/Schema.NET.Test/core/BookTest.cs
  Tests/Schema.NET.Test/core/BreadcrumbListTest.cs
  Tests/Schema.NET.Test/core/CarTest.cs
  Tests/Schema.NET.Test/core/ClaimReviewTest.cs
  Tests/Schema.NET.Test/core/CourseTest.cs
  Tests/Schema.NET.Test/core/EventTest.cs
  Tests/Schema.NET.Test/core/ItemListTest.cs
  Tests/Schema.NET.Test/core/JobPostingTest.cs
  Tests/Schema.NET.Test/core/MusicAlbumTest.cs
  Tests/Schema.NET.Test/core/MusicEventTest.cs
  Tests/Schema.NET.Test/core/MusicGroupTest.cs
  Tests/Schema.NET.Test/core/MusicRecordingTest.cs
  Tests/Schema.NET.Test/core/MusicVenueTest.cs
  Tests/Schema.NET.Test/core/NewsArticleTest.cs
  Tests/Schema.NET.Test/core/OrganizationTest.cs
  Tests/Schema.NET.Test/core/PersonTest.cs
  Tests/Schema.NET.Test/core/ProductTest.cs
  Tests/Schema.NET.Test/core/RecipeTest.cs
  Tests/Schema.NET.Test/core/RestaurantTest.cs
  Tests/Schema.NET.Test/core/TestDefaults.cs
  Tests/Schema.NET.Test/core/VideoObjectTest.cs
  Tools/Schema.NET.Tool/Services/EnumerationValueComparer.cs
  Tools/Schema.NET.Tool/Services/PropertyNameComparer.cs
  Tools/Schema.NET.Tool/ViewModels/PropertyType.cs
Labels: maintenance, patch

#255 Bump Cake.Tool from 1.0.0 to 1.1.0
  build.cake
  dotnet-tools.json
  global.json
Labels: maintenance, patch

#262 Source generator tweaks
  Tools/Schema.NET.Tool/CustomOverrides/AddQueryInputPropertyToSearchAction.cs
  Tools/Schema.NET.Tool/CustomOverrides/RenameEventProperty.cs
  Tools/Schema.NET.Tool/GeneratorModels/GeneratorSchemaClass.cs
  Tools/Schema.NET.Tool/GeneratorModels/GeneratorSchemaEnumeration.cs
  Tools/Schema.NET.Tool/GeneratorModels/GeneratorSchemaEnumerationValue.cs
  Tools/Schema.NET.Tool/GeneratorModels/GeneratorSchemaObject.cs
  Tools/Schema.NET.Tool/GeneratorModels/GeneratorSchemaProperty.cs
  Tools/Schema.NET.Tool/Models/SchemaClass.cs
  Tools/Schema.NET.Tool/Models/SchemaEnumerationValue.cs
  Tools/Schema.NET.Tool/Models/SchemaObject.cs
  Tools/Schema.NET.Tool/Models/SchemaProperty.cs
  Tools/Schema.NET.Tool/Repositories/SchemaPropertyJsonConverter.cs
  Tools/Schema.NET.Tool/Repositories/SchemaRepository.cs
  Tools/Schema.NET.Tool/SchemaSourceGenerator.cs
  Tools/Schema.NET.Tool/Services/SchemaService.cs
Labels: enhancement

#264 Further Nullable Improvements
  Source/Schema.NET/DateTimeHelper.cs
  Source/Schema.NET/EnumHelper.cs
  Source/Schema.NET/ValuesJsonConverter.cs
Labels: enhancement, patch
