Repository RehanSaeed/Schema.NET, pull requests merged in 2021-06, with the labels that each got.

#294 Add Microsoft Cross-Platform Code Coverage
  Tests/Directory.Build.props
  build.cake
Labels: maintenance, patch

#295 Update global.json to .NET 5.0.301
  global.json
Labels: maintenance, patch

#297 Add NuGet Package Downloads
  README.md
Labels: documentation, patch

#301 Improve source generator usage
  Data/schemaorg-all-https.jsonld
  Schema.NET.sln
  Tools/Schema.NET.Tool/Properties/launchSettings.json
  Tools/Schema.NET.Tool/Repositories/SchemaRepository.cs
  Tools/Schema.NET.Tool/Samples/schemaorg-all-https.jsonld
  Tools/Schema.NET.Tool/Samples/tree.jsonld
  Tools/Schema.NET.Tool/Schema.NET.Tool.csproj
  Tools/Schema.NET.Tool/SchemaSourceGenerator.cs
  Tools/Schema.NET.Updater/Program.cs
  Tools/Schema.NET.Updater/Schema.NET.Updater.csproj
Labels: enhancement, maintenance, patch

#304 Document New Schema.Net.Pending Package
  README.md
Labels: documentation, patch
